# Generated by Django 5.0.2 on 2024-02-10 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service_Category',
        ),
    ]
