# Generated by Django 5.0.2 on 2024-02-10 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_regions_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='districts',
            old_name='name',
            new_name='district_regoin',
        ),
    ]
