# Generated by Django 5.0.2 on 2024-02-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_rename_name_districts_district_regoin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='districts',
            old_name='district_regoin',
            new_name='district_region',
        ),
    ]
