# Generated by Django 5.0.2 on 2024-02-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_rename_district_regoin_districts_district_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='districts',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
