# Generated by Django 5.0.2 on 2024-02-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_districts_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='districts',
            old_name='district_region',
            new_name='region',
        ),
    ]
