# Generated by Django 5.0.2 on 2024-02-10 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='imo',
            field=models.CharField(default='salam', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(default='salam', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='+99363565353', max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format +9936XXXXXXX or +9937XXXXXXX, where XXXXXXX is the 7-digit subscriber number.', regex='^\\+(?:9936|9937)\\d{7}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='tiktok',
            field=models.CharField(default='salam', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='webpage',
            field=models.URLField(default='https://gemini.google.com/app/f94a429780aa892d'),
        ),
    ]
