# Generated by Django 5.0.2 on 2024-02-10 04:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_user_fullname_user_imo_user_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format +9936XXXXXXX or +9937XXXXXXX, where XXXXXXX is the 7-digit subscriber number.', regex='^\\+(?:9936|9937)\\d{7}$')]),
        ),
    ]
