# Generated by Django 5.0.2 on 2024-02-10 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format +99361-->65XXXXXX or +99371XXXXXX, where XXXXXXX is the 7-digit subscriber number.', regex='^\\+(?:99361|99362|99363|99364|99365|99371)\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='tiktok',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='webpage',
            field=models.URLField(blank=True),
        ),
    ]
