# Generated by Django 5.0.2 on 2024-02-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_imo_alter_user_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.FloatField(default=0),
        ),
    ]
