# Generated by Django 5.0.2 on 2024-02-13 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_service_category_image'),
        ('users', '0010_liked_user_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', through='users.Liked', to='services.services'),
        ),
        migrations.CreateModel(
            name='Viewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed-user+', to=settings.AUTH_USER_MODEL)),
                ('viewing_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing-user+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='viewed',
            field=models.ManyToManyField(related_name='viewing', through='users.Viewing', to=settings.AUTH_USER_MODEL),
        ),
    ]
