# Generated by Django 5.0.2 on 2024-02-13 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_favorites_viewing_user_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='111 house, LLLLLLLLLLLLLLL street, PPPPPPPPPPPPPPP city, DDDDDDDDDD region', max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid address format. Please use the correct format: xxx house, LLLLLLLLLLLLLLL street, PPPPPPPPPPPPPPP city, DDDDDDDDDD region.', regex='^(?P<house_number>\\d{3}) house, (?P<street>[A-Z]{15}), (?P<city>[A-Z]{15}), (?P<region>[A-Z]{10})$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='banner_image',
            field=models.ImageField(default='products/2024/02/11/2150796722.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.IntegerField(default=1),
        ),
    ]
