# Generated by Django 5.0.2 on 2024-02-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_about_alter_user_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favorites',
            new_name='favorite_services',
        ),
    ]
