# Generated by Django 5.0.2 on 2024-02-13 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_favorites_user_favorite_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favoriting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriting-user+', to=settings.AUTH_USER_MODEL)),
                ('fovarited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited-user+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_users',
            field=models.ManyToManyField(related_name='favorited_user_by', through='users.LikedUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
