# Generated by Django 5.0.2 on 2024-02-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_likedusers_user_favorite_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedusers',
            old_name='fovarited_user',
            new_name='favorited_user',
        ),
    ]
