# Generated by Django 5.0.2 on 2024-02-14 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_service_category_image'),
        ('users', '0017_rename_fovarited_user_likedusers_favorited_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewed_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='viewed_services',
            field=models.ManyToManyField(related_name='viewed_by', through='users.Viewed_Service', to='services.services'),
        ),
    ]
