# Generated by Django 5.0.2 on 2024-02-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_viewed_service_user_viewed_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_services',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite_users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='viewed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='viewed_services',
        ),
    ]
