# Generated by Django 5.0.2 on 2024-02-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_user_favorite_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedusers',
            name='favorited_user',
        ),
        migrations.RemoveField(
            model_name='likedusers',
            name='favoriting_user',
        ),
        migrations.RemoveField(
            model_name='viewed_service',
            name='service',
        ),
        migrations.RemoveField(
            model_name='viewed_service',
            name='user',
        ),
        migrations.RemoveField(
            model_name='viewing',
            name='viewed_user',
        ),
        migrations.RemoveField(
            model_name='viewing',
            name='viewing_user',
        ),
        migrations.DeleteModel(
            name='Liked',
        ),
        migrations.DeleteModel(
            name='LikedUsers',
        ),
        migrations.DeleteModel(
            name='Viewed_Service',
        ),
        migrations.DeleteModel(
            name='Viewing',
        ),
    ]
