# Generated by Django 5.0.2 on 2024-02-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_likedusers_favorited_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count_point',
            field=models.IntegerField(default=0),
        ),
    ]
