# Generated by Django 5.0.2 on 2024-02-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_count_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='all_point_total',
            field=models.IntegerField(default=0),
        ),
    ]
