# Generated by Django 5.0.2 on 2024-02-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_user_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='view_counter',
            field=models.IntegerField(default=0),
        ),
    ]
