# Generated by Django 5.0.2 on 2024-02-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_user_view_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_counter',
            field=models.IntegerField(default=0),
        ),
    ]
