# Generated by Django 5.0.2 on 2024-02-16 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_user_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='about',
            new_name='summary',
        ),
    ]
