# Generated by Django 5.0.2 on 2024-02-16 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_rename_about_user_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='webpage',
            new_name='web',
        ),
    ]
