# Generated by Django 5.0.2 on 2024-02-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_rename_phone_number_user_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='point',
            new_name='rate_point',
        ),
    ]
