# Generated by Django 5.0.2 on 2024-02-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_rename_point_user_rate_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='all_point_total',
            new_name='rate_point_total',
        ),
    ]
