# Generated by Django 5.0.2 on 2024-02-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_rename_all_point_total_user_rate_point_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='count_point',
            new_name='point_counter',
        ),
    ]
