# Generated by Django 5.0.2 on 2024-02-14 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_alter_rate_rated_user_alter_rate_rating_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewing',
            name='viewed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viewing',
            name='viewing_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
