# Generated by Django 5.0.2 on 2024-02-14 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_alter_viewing_viewed_user_alter_viewing_viewing_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedusers',
            name='favorited_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likedusers',
            name='favoriting_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriting_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
