# Generated by Django 5.0.2 on 2024-02-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0007_alter_likedusers_favorited_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='five',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='four',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='one',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='three',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='two',
        ),
        migrations.AddField(
            model_name='rate',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rate',
            name='score_count',
            field=models.IntegerField(default=0),
        ),
    ]
