# Generated by Django 5.0.2 on 2024-02-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0008_remove_rate_five_remove_rate_four_remove_rate_one_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='score',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='score_count',
        ),
        migrations.AddField(
            model_name='rate',
            name='rate_number',
            field=models.IntegerField(default=0),
        ),
    ]
