# Generated by Django 5.0.2 on 2024-02-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0009_remove_rate_score_remove_rate_score_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate_number',
            field=models.IntegerField(),
        ),
    ]
