# Generated by Django 5.0.2 on 2024-02-16 06:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0010_alter_rate_rate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedusers',
            name='liked_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
