# Generated by Django 5.0.2 on 2024-02-16 06:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0011_likedusers_liked_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='liked',
            name='liked_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
