# Generated by Django 5.0.2 on 2024-02-16 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0012_liked_liked_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liked',
            old_name='liked_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='likedusers',
            old_name='liked_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='rated_time',
            new_name='date_created',
        ),
    ]
