# Generated by Django 5.0.2 on 2024-02-16 11:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0014_rename_liked_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikedUsers',
            new_name='Like_User',
        ),
    ]
