# Generated by Django 5.0.2 on 2024-02-16 11:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0015_rename_likedusers_like_user'),
        ('services', '0015_services_like_counter_services_view_counter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Viewed_Service',
            new_name='View_Service',
        ),
    ]
