# Generated by Django 5.0.2 on 2024-02-16 11:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0016_rename_viewed_service_view_service'),
        ('services', '0015_services_like_counter_services_view_counter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='Like_Service',
        ),
    ]
