# Generated by Django 5.0.2 on 2024-02-16 11:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0017_rename_like_like_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Viewing',
            new_name='View_User',
        ),
    ]
