# Generated by Django 5.0.2 on 2024-02-16 11:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0018_rename_viewing_view_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rate',
            new_name='Rate_User',
        ),
    ]
