# Generated by Django 5.0.2 on 2024-02-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodGalleryImage',
            new_name='ServiceGalleryImage',
        ),
    ]
