# Generated by Django 5.0.2 on 2024-02-12 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_goodgalleryimage_servicegalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.services'),
        ),
    ]
