# Generated by Django 5.0.2 on 2024-02-12 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_servicegalleryimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.services'),
        ),
    ]
