# Generated by Django 5.0.2 on 2024-02-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_servicegalleryimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='image',
            field=models.ImageField(upload_to='products/product_gallery_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='primary_image',
            field=models.ImageField(max_length=255, upload_to='products/product_images/%Y/%m/%d/'),
        ),
    ]
