# Generated by Django 5.0.2 on 2024-02-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_servicegalleryimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_category',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='categories/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='products/product_gallery_images/%Y/%m/%d/'),
        ),
    ]
