# Generated by Django 5.0.2 on 2024-02-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_service_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_category',
            name='image',
            field=models.ImageField(default='/products/2024/02/12/2150780328_d7wyOtY.jpg', max_length=255, upload_to='categories/%Y/%m/%d/'),
        ),
    ]
