# Generated by Django 5.0.2 on 2024-02-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_service_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_category',
            name='image',
            field=models.ImageField(max_length=255, upload_to='categories/%Y/%m/%d/'),
        ),
    ]
