# Generated by Django 5.0.2 on 2024-02-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_service_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='service/service_gallery_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='primary_image',
            field=models.ImageField(max_length=255, upload_to='service/service_images/%Y/%m/%d/'),
        ),
    ]
