# Generated by Django 5.0.2 on 2024-02-15 08:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_servicegalleryimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='vip_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='services',
            name='vip_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
