# Generated by Django 5.0.2 on 2024-02-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_services_vip_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='vip_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
