# Generated by Django 5.0.2 on 2024-02-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_services_vip_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='like_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='services',
            name='view_counter',
            field=models.IntegerField(default=0),
        ),
    ]
