# Generated by Django 5.0.2 on 2024-02-16 12:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_rename_name_districts_district'),
        ('ratings', '0019_rename_rate_rate_user'),
        ('services', '0015_services_like_counter_services_view_counter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
