# Generated by Django 5.0.2 on 2024-02-13 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementmodel',
            name='expired_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 13, 18, 2, 47, 904949)),
        ),
        migrations.AddField(
            model_name='advertisementmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
