# Generated by Django 5.0.2 on 2024-02-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_advertisementmodel_expired_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementmodel',
            name='expired_date',
            field=models.DateField(),
        ),
    ]
