# Generated by Django 5.0.2 on 2024-02-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_alter_advertisementmodel_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementmodel',
            name='image',
            field=models.ImageField(max_length=255, upload_to='advertisements/%Y/%m/%d/'),
        ),
    ]
